sitemanager/urls.py
from django.urls import path, include

from sitemanager import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('user_profile/<int:pid1>/', views.user_profile, name='user_profile'),
    path('user_create/', views.user_create, name='user_create'),
    path('user_edit_details/<int:pid1>/', views.user_edit_details, name='user_edit_details'),
    path('user_view/', views.user_view, name='user_view'),
    path('user_change_password/<int:pid1>/', views.user_change_password, name='user_change_password'),
    path('user_change_jobrole/<int:pid3>/', views.user_change_group, name='user_change_jobrole'),
    path('deletemsg/<int:msgid>/', views.deletemsg, name='deletemsg'),
    path('threesaillconnectionsoverallleads/', views.threesaillconnectionsoverallleads,
         name='threesaillconnectionsoverallleads'),
    path('threesaillconnectionsoverallleads/<int:cid>/edit', views.editillconn, name='editillconn'),
    path('illvendor/', views.illvendor, name='illvendor'),
    path('illvendor/add', views.addillvendor, name='addillvendor'),
    path('illvendor/<int:evid>/edit', views.editillvendor, name='editillvendor'),
    path('ohfandugfvendor/', views.ohfandugfvendor, name='ohfandugfvendor'),
    path('ohfandugfvendor/add', views.addohfandugfvendor, name='addohfandugfvendor'),
    path('ohfandugfvendor/<int:eoauvid>/edit', views.editiohfandugfvendor, name='editiohfandugfvendor'),
    path('shift-connection/', views.shiftconnection, name='shiftconnection'),
    path('shift-connection/<str:ccid>', views.shiftconncheck, name='shiftconncheck'),
    path('shift-connection-verify/', views.shiftconnverify, name='shiftconnverify'),
    path('shift-connection-history/', views.shiftconnhistory, name='shiftconnhistory'),
    path('3saipping/<str:pipaddress>', views.threesaipping, name='3saipping'),
    path('location/', views.threesalocation, name='location'),
    path('downloadbackupdata/', views.downloadbackupdata, name='downloadbackupdata'),
    path('showbillinghistory/<str:connid>', views.showbillinghistory, name='showbillinghistory'),

]

threesaillmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('db-admin/', admin.site.urls),
    path('', include('sitemanager.urls')),
    path('threesaillconnections/', include('threesaillconnections.urls')),
    path('ttvillconnections/', include('threesaillthroughvendors.urls')),
    path('vttillconnections/', include('vendorsillthroughthreesa.urls')),
    path('ohfandugf/', include('ohfandugfmanager.urls')),
    path('netoperators/', include('threesaoperators.urls')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemanager/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, username, password, **extra_fields):
        extra_fields.setdefault('is_superuser', False)

        if not username:
            raise ValueError('The Username must be set')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self.create_user(username, password, **extra_fields)


class User(AbstractUser):
    first_name = None
    last_name = None
    user_full_name = models.CharField(max_length=100, null=True)
    user_mobile = models.IntegerField(null=True)
    user_image = models.ImageField(blank=True, null=True, upload_to='profileimages/', )
    objects = UserManager()

    class Meta:
        verbose_name_plural = '1. Users'

    def __str__(self):
        return self.username


class IllVendors(models.Model):
    v_code = models.CharField(verbose_name='vendor code', max_length=255, unique=True)
    v_name = models.CharField(verbose_name='vendor name', max_length=255)
    v_contactno = models.CharField(verbose_name='vendor contact number', max_length=255)
    v_address = models.CharField(verbose_name='vendor address', max_length=255)
    v_kyc = models.FileField(verbose_name='Upload kyc details', upload_to='vendorskyc/',
                             blank=True)
    v_gstno = models.CharField(verbose_name='vendor GST number', max_length=255)

    class Meta:
        verbose_name_plural = '2. ILL Vendors'

    def __str__(self):
        return self.v_code


class ThreesaIllConnectionsDetails(models.Model):
    FBOOL_CHOICES = ((True, 'Possible'), (False, 'Not Possible'))
    ASBOOL_CHOICES = ((True, 'Assigned'), (False, 'Not Assigned'))
    conn_type = (('1', 'Threesa'), ('2', 'Threesa Through Vendor'), ('3', 'Vendor Through Threesa'))
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Connection Code')
    ill_custid = models.CharField(verbose_name='Connection Id', max_length=255, unique=True)
    ill_gendate = models.DateTimeField(verbose_name='Lead Generation Date', auto_now_add=True)
    ill_cust_name = models.CharField(verbose_name='Customer Name', max_length=255)
    ill_cust_address = models.TextField(verbose_name='Customer Address')
    ill_cust_address_lat = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    ill_cust_address_long = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    ill_conn_type = models.CharField(verbose_name='Connection Type', max_length=255, choices=conn_type, default=1)
    ill_vendor_code = models.ForeignKey(IllVendors, models.SET_NULL, verbose_name='vendor details', blank=True,
                                        null=True)
    ill_sales_person = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Sales Person Name',
                                         limit_choices_to={'groups__name': 'salesperson'}, )
    ill_feasibility = models.BooleanField(choices=FBOOL_CHOICES, verbose_name='Feasibility Status', default=False)
    ill_sign_id = models.CharField(verbose_name='sign id', max_length=255, null=True, blank=True)
    ill_sign_time = models.DateTimeField(verbose_name='sign time', null=True, blank=True)
    assign_status = models.BooleanField(choices=ASBOOL_CHOICES, verbose_name='assign status', default=False, )

    class Meta:
        verbose_name_plural = '6. ILL Connections'

    def __str__(self):
        return self.ill_custid


class RejectionMessage(models.Model):
    msg_sender = models.CharField(max_length=255)
    msg_receiver = models.CharField(max_length=255)
    conn_code = models.CharField(max_length=255)
    rej_module_name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = '9. ILL Rejection Message'

    def __str__(self):
        return str(self.id)


class IllNotification(models.Model):
    conn_type = (('1', 'Threesa'), ('2', 'Threesa Through Vendor'), ('3', 'Vendor Through Threesa'))

    conn_code = models.ForeignKey(ThreesaIllConnectionsDetails, on_delete=models.SET_NULL,
                                  verbose_name='Ill Connection ID', blank=True, null=True)
    link_code = models.CharField(verbose_name='Link Code', max_length=255, blank=True, null=True)
    ill_prev_assign_obj_id = models.IntegerField(verbose_name="Previous id")
    ill_ntfc_sender = models.CharField(verbose_name='Notification Sender', max_length=255, blank=True)
    ill_ntfc_receiver = models.CharField(verbose_name='Notification Receiver', max_length=255, blank=True)
    assign_date_time = models.DateTimeField(verbose_name='Assign Time')
    accept_mod_url = models.CharField(verbose_name='Accept Url', max_length=255, blank=True)
    reject_mod_url = models.CharField(verbose_name='Reject Url', max_length=255, blank=True)
    ill_app_name = models.CharField(verbose_name='ILL App Name', max_length=255, blank=True, choices=conn_type)

    class Meta:
        verbose_name_plural = '8. ILL Notification'

    def __str__(self):
        return str(self.id)


class IllConnectionShiftHistory(models.Model):
    shifter_user = models.CharField(verbose_name='Shifter Username', max_length=255)
    shift_conn_id = models.CharField(verbose_name='Shifted connection id', max_length=255)
    shift_from = models.CharField(verbose_name='Shifted from', max_length=255)
    shift_to = models.CharField(verbose_name='Shifted to', max_length=255)
    shift_date = models.DateTimeField(verbose_name='shifted Date')

    class Meta:
        verbose_name_plural = '7. ILL Connection Shift History'

    def __str__(self):
        return str(self.id)


class IllBillingHistory(models.Model):
    paymentstatus = (
        ('1', 'Done'),
        ('2', 'Pending'),
    )
    paymentmethod = (
        ('1', 'Cash'),
        ('2', 'NetBanking'),
        ('3', 'Cheque'),
    )
    NetBankingType = (
        ('1', 'NEFT'),
        ('2', 'IMPS'),
        ('3', 'RTGS'),
        ('4', 'UPI'),
    )
    conn_code = models.CharField(verbose_name='Connection Id', max_length=255, null=True, blank=True)
    conn_type = models.CharField(verbose_name='Connection Type', max_length=255, null=True, blank=True)
    assign_date_time = models.DateTimeField(verbose_name='Assign Date Time', blank=True, null=True)
    conn_start_date = models.DateField(verbose_name='Connection Start Date', blank=True, null=True)
    conn_end_date = models.DateField(verbose_name='Connection End Date', blank=True, null=True)
    bandwidth = models.CharField(verbose_name='Bandwidth', max_length=255, null=True, blank=True)
    link_validity = models.CharField(verbose_name='Link Validity', max_length=255, null=True, blank=True)
    payment_method = models.CharField(verbose_name='Payment Method', max_length=20, choices=paymentmethod,
                                      blank=True, null=True)
    netbanking_type = models.CharField(verbose_name='Netbanking Type', max_length=20, choices=NetBankingType,
                                       default='1', blank=True, null=True)
    transaction_id = models.CharField(verbose_name='Transaction Id', max_length=255, blank=True, null=True)
    payment_status = models.CharField(verbose_name='Payment Status', max_length=20, choices=paymentstatus, default='2')
    amount = models.CharField(verbose_name='Amount', max_length=255, blank=True, null=True)
    transaction_receipt = models.FileField(verbose_name='Transaction Receipt', upload_to='illdata/transaction/',
                                           blank=True, null=True)
    billing_img = models.FileField(verbose_name='Invoice', upload_to='illdata/billingimages/', blank=True)
    ill_billing_receiver = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name_plural = 'ILL Billing History'

templates/threesaapptemp/add_ill_billing.html
{% extends "base.html" %}
{% load static %}
{% block blockjs%}
<script type="text/javascript">
$(document).ready(function() {
    $("#paym1").hide();
    $("#paym2").hide();
    $("#paym3").hide();

    function checkpmode() {
        if ($('#id_payment_method option:selected').val() == '1') {
            $('#paymentmode').html($('#paym1').html());

        } else if ($('#id_payment_method option:selected').val() == '2') {
            $('#paymentmode').html($('#paym2').html());

        } else if ($('#id_payment_method option:selected').val() == '3') {

            $('#paymentmode').html($('#paym3').html());
        } else {
            $('#paymentmode').html('');

        }
    }
    checkpmode();

    function validitycal(sdat, edat) {
        var d1 = Date.parse(sdat);
        var d2 = Date.parse(edat);
        if (d1 < d2) {
            var date1 = new Date(edat);
            var date2 = new Date(sdat);
            var diffTime = Math.abs(date2 - date1);
            var diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
            $("#id_link_validity").val(diffDays);
        } else {

            $("#id_link_validity").val('0');
        }

    }
    validitycal($('#id_conn_start_date').val(), $('#id_conn_end_date').val());
    $("#id_payment_method").on("change", function() {
        checkpmode();
    });

    $('#id_conn_start_date').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
        minYear: 1990,
        maxYear: 2121,
    }, function(start, end, label) {
        $(this).val(start);
        endd = $('#id_conn_end_date').val();
        validitycal(start, endd)

    });

    $('#id_conn_end_date').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
        minYear: 1990,
        maxYear: 2121,
    }, function(start, end, label) {
        $(this).val(start);
        var startd = $("#id_conn_start_date").val();
        validitycal(startd, start);
    });


});
</script>
{% endblock %}
{% block maincontent %}
<header class="page-header">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">Add ILL Connection Billing Details</h2>
    </div>
</header>
<!-- Breadcrumb-->
<div class="breadcrumb-holder container-fluid">
    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index'%}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'threesaillconnections'%}">ThreesaILLConnections</a></li>
        <li class="breadcrumb-item">Threesa IIL Connection Billing Details</li>
        <li class="breadcrumb-item active">Add</li>
    </ul>
</div>
<!--Create User Form-->
<section class="forms">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header d-flex align-items-center">
                        <h3 class="h4">Add ILL Connection Billing Details</h3>
                    </div>
                    <div class="card-body">
                        <form class="form-horizontal" method="POST" enctype="multipart/form-data">
                            {%csrf_token%}
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Connection Id</label>
                                <div class="col-sm-9">
                                    {{objbn.conn_code}}
                                    {{form.conn_code}}
                                    {% if form.conn_code.errors %}
                                    <small class="help-block-none">{{form.conn_code.errors}}</small>
                                    {% endif%}
                                </div>
                            </div>
                            <div class="line"></div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Assigned Date and time</label>
                                <div class="col-sm-9">
                                    {{objbn.assign_date_time}}
                                </div>
                            </div>
                            <div class="line"></div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Connection Start Date</label>
                                <div class="col-sm-9">
                                    {{form.conn_start_date}}
                                    {% if form.conn_start_date.errors %}
                                    <small class="help-block-none">{{form.conn_start_date.errors}}</small>
                                    {% endif%}
                                </div>
                            </div>
                            <div class="line"></div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Connection End Date</label>
                                <div class="col-sm-9">
                                    {{form.conn_end_date}}
                                    {% if form.conn_end_date.errors %}
                                    <small class="help-block-none">{{form.conn_end_date.errors}}</small>
                                    {% endif%}
                                </div>
                            </div>
                            <div class="line"></div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">ILL Validity (In Days)</label>
                                <div class="col-sm-9">
                                    {{form.link_validity}}
                                    {% if form.link_validity.errors %}
                                    <small class="help-block-none">{{form.link_validity.errors}}</small>
                                    {% endif%}
                                </div>
                            </div>
                            <div class="line"></div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">ILL Bandwidth (In Mbps)</label>
                                <div class="col-sm-9">
                                    {{form.bandwidth}}
                                    {% if form.bandwidth.errors %}
                                    <small class="help-block-none">{{form.bandwidth.errors}}</small>
                                    {% endif%}
                                </div>
                            </div>
                            <div class="line"></div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Payment Status</label>
                                <div class="col-sm-9">
                                    {{form.payment_status}}
                                    {% if form.payment_status.errors %}
                                    <small class="help-block-none">{{form.payment_status.errors}}</small>
                                    {% endif%}
                                </div>
                            </div>
                            <div class="line"></div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Amount(₹)</label>
                                <div class="col-sm-9">
                                    {{form.amount}}
                                    {% if form.amount.errors %}
                                    <small class="help-block-none">{{form.amount.errors}}</small>
                                    {% endif%}
                                </div>
                            </div>
                            <div class="line"></div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Payment Method</label>
                                <div class="col-sm-9">
                                    {{form.payment_method}}
                                    {% if form.payment_method.errors %}
                                    <small class="help-block-none">{{form.payment_method.errors}}</small>
                                    {% endif%}
                                </div>
                            </div>
                            <div id="paymentmode">
                            </div>
                            <div class="line"></div>
                            <div class="form-group row">
                                <label class="col-sm-3 form-control-label">Invoice</label>
                                <div class="col-sm-9">
                                    {{form.billing_img}}
                                    {% if form.billing_img.errors %}
                                    <small class="help-block-none">{{form.billing_img.errors}}</small>
                                    {% endif%}
                                </div>
                            </div>
                            <div class="line"></div>
                            <div class="form-group row">
                                <div class="col-sm-4 offset-sm-3">
                                    <a href="{% url 'threesaillconnections' %}" class="btn btn-secondary">Cancel</a>
                                    <input type="submit" name="submit" value="save" class="btn btn-primary">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div id="paym3">
            <div class="line">
            </div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label">
                    Cheque Number
                </label>
                <div class="col-sm-9"> {{ form.transaction_id }} {% if form.transaction_id.errors %}
                    <small class="help-block-none">{{form.transaction_id.errors}}</small> {% endif %}
                </div>
            </div>
            <div class="line"> </div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label">
                    Cheque
                </label>
                <div class="col-sm-9"> {{ form.transaction_receipt }} {% if form.transaction_receipt.errors %}
                    <small class="help-block-none">{{form.transaction_receipt.errors}}</small> {% endif %} </div>
            </div>
        </div>
    </div>
    <div>
        <div id='paym2'>
            <div class="line "></div>
            <div class="form-group row ">
                <label class="col-sm-3 form-control-label"> NetBanking Type </label>
                <div class="col-sm-9">{{form.netbanking_type}} {% if form.netbanking_type.errors %}
                    <small class="help-block-none">{{form.netbanking_type.errors}}</small> {% endif %}
                </div>
            </div>
            <div class="line"></div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label">
                    Transaction ID
                </label>
                <div class="col-sm-9">{{ form.transaction_id }} {% if form.transaction_id.errors %}
                    <small class="help-block-none">{{form.transaction_id.errors}}</small> {% endif %} </div>
            </div>
            <div class="line"></div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label">
                    Transaction Receipt
                </label>
                <div class="col-sm-9">{{ form.transaction_receipt }} {% if form.transaction_receipt.errors %}
                    <small class="help-block-none">{{form.transaction_receipt.errors}}</small> {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div>
        <div id='paym1'>
            <div class="line"></div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label">
                    Receipt Number
                </label>
                <div class="col-sm-9">{{ form.transaction_id }} {% if form.transaction_id.errors %}
                    <small class="help-block-none">{{form.transaction_id.errors}}</small> {% endif %} </div>
            </div>
            <div class="line"></div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label">
                    Receipt
                </label>
                <div class="col-sm-9">{{ form.transaction_receipt }} {% if form.transaction_receipt.errors %}
                    <small class="help-block-none">{{form.transaction_receipt.errors}}</small> {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock maincontent %}

templates/threesaapptemp/thistorymodel.html
<div id="mybilling" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" class="modal fade text-left">
    <div role="document" class="modal-dialog modal-dialog-pkghis">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="exampleModalLabel" class="modal-title">Billing History</h4>    
                <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Sr.No.</th>
                                <th>Connection ID</th>
                                <th>Connection Type</th>
                                <th>Assign Date And Time</th>
                                <th>Activation Date</th>
                                <th>Expiry Date</th>
                                <th>Bandwidth</th>
                                <th>Payment Status</th>
                                <th>Amount(₹)</th>
                                <th>Payment Method</th>
                                <th>Netbanking Type</th>
                                <th>Transaction Id</th>
                                <th>Transaction Receipt</th>
                                <th>Invoice</th>
                                <th>Accountant ID</th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for objbillingh in objbillinghs %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{objbillingh.conn_code}}</td>
                                <td>{{objbillingh.conn_type}}</td>
                                <td>{{objbillingh.assign_date_time}}</td>
                                <td>{{objbillingh.conn_start_date}}</td>
                                <td>{{objbillingh.conn_end_date}}days</td>
                                <td>{{objbillingh.bandwidth}}Mbps</td>
                                <td>{{objbillingh.get_payment_status_display}}</td>
                                <td>{{objbillingh.amount}}</td>
                                <td>{{objbillingh.get_payment_method_display}}</td>
                                <td>{{objbillingh.get_netbanking_type_display}}</td>
                                <td>{{objbillingh.transaction_id}}</td>
                                <td><a href="{{objbillingh.transaction_receipt.url}}" target="_blank">view</a></td>
                                <td><a href="{{objbillingh.billing_img.url}}" target="_blank">view</a></td>
                                <td>{{objbillingh.ill_billing_receiver}}</td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <form id='exptexcbillform' action="{% url 'showbillinghistory' connid=connid %}" method="POST">
                    {%csrf_token%}
                    <input type="hidden" name="exportexcelbillhistory" value="exportexcelbillhistory">
                    <button type="submit" class="btn btn-secondary" style="float: right;">Export Excel</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>